/*
Braxton Phillips
M08 Midterm Project 
Due March 12,2021
*/

CREATE TABLE "RENTAL_HISTORY"
    ("MEDIA_ID" NUMBER(10,0) CONSTRAINT "MEDIA_ID_NN" NOT NULL ENABLE,
    "RENTAL_DATE" DATE CONSTRAINT "RENTAL_DATE_NN" NOT NULL ENABLE,
    "CUSTOMER_ID" NUMBER(10,0) CONSTRAINT "CUSTOMER_ID_NN" NOT NULL ENABLE,
    "RETURN_DATE" DATE CONSTRAINT "RETURN_DATE_NN" NOT NULL ENABLE,
    CONSTRAINT "RENTAL_HISTORY_PK" PRIMARY KEY (MEDIA_ID, RENTAL_DATE)
USING INDEX ENABLE
);

ALTER TABLE  "RENTAL_HISTORY" ADD CONSTRAINT "CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "CUSTOMER_IDS" ("CUSTOMER_ID") ENABLE;
ALTER TABLE  "RENTAL_HISTORY" ADD CONSTRAINT "MEDIA_ID_FK" FOREIGN KEY ("MEDIA_ID")
    REFERENCES "MEDIA_IDS" ("MEDIA_ID") ENABLE;

CREATE TABLE "MEDIA"
    ("MEDIA_ID" NUMBER(10,0) CONSTRAINT "MEDIA_ID_NN" NOT NULL ENABLE,
    "FORMAT" VARCHAR2(3 BYTE) CONSTRAINT "FORMAT_NN" NOT NULL ENABLE,
    "TITLE_ID" NUMBER(10,0) CONSTRAINT "TITLE_ID_NN" NOT NULL ENABLE,
    CONSTRAINT "MEDIA_ID_PK" PRIMARY KEY (MEDIA_ID)
USING INDEX ENABLE
);

ALTER TABLE  "MEDIA" ADD CONSTRAINT "MEDIA_TITLEID_FK" FOREIGN KEY ("TITLE_ID")
    REFERENCES "TITLE_IDS" ("TITLE_ID") ENABLE;

CREATE TABLE "STAR_BILLINGS"
    ("ACTOR_ID" NUMBER(10,0) CONSTRAINT "ACTOR_ID_NN" NOT NULL ENABLE,
    "TITLE_ID" NUMBER(10,0) CONSTRAINT "TITLE_ID_NN" NOT NULL ENABLE,
    "COMMENTS" VARCHAR2(40 BYTE),
    CONSTRAINT "STAR_BILLINGS_PK" PRIMARY KEY (ACTOR_ID, TITLE_ID)
USING INDEX ENABLE
);

ALTER TABLE  "STAR_BILLINGS" ADD CONSTRAINT "ACTOR_ID_FK" FOREIGN KEY ("ACTOR_ID")
    REFERENCES "ACTOR_IDS" ("ACTOR_ID") ENABLE;
ALTER TABLE  "STAR_BILLINGS" ADD CONSTRAINT "TITLE_ID_FK" FOREIGN KEY ("TITLE_ID")
    REFERENCES "TITLE_IDS" ("TITLE_ID") ENABLE;

CREATE TABLE "MOVIES"
    ("TITLE_ID" NUMBER(10,0) CONSTRAINT "TITLE_ID_NN" NOT NULL ENABLE,
    "TITLE" VARCHAR2(60 BYTE) CONSTRAINT "TITLE_NN" NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR2(400 BYTE) CONSTRAINT "DESCRIPTION_NN" NOT NULL ENABLE,
    "RATING" VARCHAR2(4 BYTE) CHECK ("RATING" IN ('G', 'PG', 'R', 'PG13')),
    "CATEGORY" VARCHAR2(20 BYTE) CHECK ("CATEGORY" IN ('DRAMA', 'COMEDY', 'ACTION', 'CHILD', 'SCI-FI', 'DOCUMENTARY')),
    "RELEASE_DATE" DATE CONSTRAINT "RELEASE_DATE_NN" NOT NULL ENABLE,
    CONSTRAINT "TITLE_ID_PK" PRIMARY KEY ("TITLE_ID")
USING INDEX ENABLE
);

CREATE TABLE "CUSTOMERS"
    ("CUSTOMER_ID" NUMBER(10,0) CONSTRAINT "CUSTOMER_ID_NN" NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(25 BYTE) CONSTRAINT "LAST_NAME_NN" NOT NULL ENABLE,
    "FIRST_NAME" VARCHAR2(25 BYTE) CONSTRAINT "FIRST_NAME_NN" NOT NULL ENABLE,
    "HOME_PHONE" VARCHAR2(12 BYTE) CONSTRAINT "HOME_PHONE_NN" NOT NULL ENABLE,
    "ADDRESS" VARCHAR2(100 BYTE) CONSTRAINT "ADDRESS_NN" NOT NULL ENABLE,
    "CITY" VARCHAR2(30 BYTE) CONSTRAINT "CITY_NN" NOT NULL ENABLE,
    "STATE" VARCHAR2(2 BYTE) CONSTRAINT "STATE_NN" NOT NULL ENABLE,
    "EMAIL" VARCHAR2(25 BYTE),
    "CELL_PHONE" VARCHAR2(12 BYTE),
    CONSTRAINT "CUSTOMER_ID_PK" PRIMARY KEY (CUSTOMER_ID)
USING INDEX ENABLE
);

CREATE TABLE "ACTORS"
    ("ACTOR_ID" NUMBER(10,0) CONSTRAINT "ACTOR_ID_NN" NOT NULL ENABLE,
    "STAGE_NAME" VARCHAR2(40 BYTE) CONSTRAINT "STAGE_NAME_NN" NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(25 BYTE) CONSTRAINT "LAST_NAME_NN" NOT NULL ENABLE,
    "FIRST_NAME" VARCHAR2(25 BYTE) CONSTRAINT "FIRST_NAME_NN" NOT NULL ENABLE,
    "BIRTH_DATE" DATE CONSTRAINT "BIRTH_DATE_NN" NOT NULL ENABLE,
    CONSTRAINT "ACTOR_ID_PK" PRIMARY KEY (ACTOR_ID)
USING INDEX ENABLE
);